packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.90.21
  "@trpc/client": ^11.10.0
  "@trpc/react-query": ^11.10.0
  "@trpc/server": ^11.10.0
  eslint: ^10.0.0
  prettier: ^3.8.1
  tailwindcss: ^4.2.1
  typescript: ^5.9.3
  zod: ^4.0.0

catalogs:
  react18:
    react: 19.2.4
    react-dom: 19.2.4
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
