import { execFileSync } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const SOURCE_YEAR = 2025;
const SOURCE_URL =
  "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2025_Gazetteer/2025_Gaz_place_national.zip";
const OUTPUT_PATH = new URL("../src/data/us-cities-2025.ts", import.meta.url);

const PLACE_SUFFIX =
  / (city and borough|consolidated government|metro government|unified government|municipality|borough|village|town|city|CDP|balance)$/;

const temporaryDirectory = await mkdtemp(join(tmpdir(), "forge-us-cities-"));
const archivePath = join(temporaryDirectory, "places.zip");

try {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Census download failed with ${response.status}.`);
  }

  await writeFile(archivePath, Buffer.from(await response.arrayBuffer()));
  const raw = execFileSync("unzip", ["-p", archivePath], {
    encoding: "utf8",
    maxBuffer: 20 * 1024 * 1024,
  });
  const [, ...lines] = raw.trim().split(/\r?\n/);
  const records = lines.map((line) => {
    const fields = line.split("|");
    const state = fields[0];
    const geoid = fields[1];
    const censusName = fields[4];
    const latitude = Number(fields[11]);
    const longitude = Number(fields[12]);

    if (
      !state ||
      !geoid ||
      !censusName ||
      !Number.isFinite(latitude) ||
      !Number.isFinite(longitude)
    ) {
      throw new Error(`Unexpected Census place row: ${line}`);
    }

    const name = censusName.replace(PLACE_SUFFIX, "");
    const key = `${geoid.slice(0, 2)}-${geoid.slice(2)}`;
    return [key, name, state, latitude, longitude] as const;
  });

  const output = `// Generated by scripts/generate-us-cities.ts. Do not edit by hand.
// Source: ${SOURCE_URL}
export const US_CITY_SOURCE = {
  year: ${SOURCE_YEAR},
  url: ${JSON.stringify(SOURCE_URL)},
} as const;

export type UsCityRecord = readonly [
  key: string,
  name: string,
  state: string,
  latitude: number,
  longitude: number,
];

export const US_CITIES_2025: readonly UsCityRecord[] = ${JSON.stringify(records)};
`;

  await writeFile(OUTPUT_PATH, output);
  process.stdout.write(`Generated ${records.length} U.S. Census places.\n`);
} finally {
  await rm(temporaryDirectory, { force: true, recursive: true });
}
