export const AUDITED_ADMIN_PROCEDURES = [
  "alumni.archiveBulletinPost",
  "alumni.createBulletinPost",
  "alumni.removeBulletinImage",
  "alumni.reorderBulletinPosts",
  "alumni.restoreBulletinPost",
  "alumni.updateBulletinPost",
  "alumni.uploadBulletinImage",
  "analytics.exportReport",
  "career.approveCompany",
  "career.mergeCompanies",
  "career.rejectCompany",
  "career.removeCompanyImage",
  "career.updateCompany",
  "career.uploadCompanyImage",
  "email.archiveTemplate",
  "email.cancelSend",
  "email.confirmSend",
  "email.duplicateTemplate",
  "email.previewSend",
  "email.publishTemplate",
  "email.retrySend",
  "email.saveTemplateDraft",
  "email.sendTest",
  "event.addEventFeedbackQuestion",
  "event.archiveTag",
  "event.checkInMember",
  "event.createEvent",
  "event.createTag",
  "event.deleteEvent",
  "event.deleteEventFeedbackResponse",
  "event.exportAttendance",
  "event.exportEventFeedback",
  "event.removeAttendance",
  "event.repairIntegration",
  "event.resolveDiscordProjection",
  "event.retrySync",
  "event.updateEvent",
  "event.updateFeedbackTemplate",
  "event.updateTag",
  "forms.changeState",
  "forms.configureCallback",
  "forms.createForm",
  "forms.createSection",
  "forms.deleteForm",
  "forms.deleteResponse",
  "forms.disableCallback",
  "forms.exportResponses",
  "forms.retryCallback",
  "forms.updateForm",
  "forms.updateSection",
  "forms.updateSettings",
  "issues.archive",
  "issues.create",
  "issues.createTemplate",
  "issues.disableTemplate",
  "issues.restore",
  "issues.update",
  "issues.updateTemplate",
  "member-admin.accessAdminMemberResume",
  "member-admin.deleteAdminMember",
  "member-admin.exportAdminMembers",
  "member-admin.invalidateEffectiveDues",
  "member-admin.removeAdminProfilePicture",
  "member-admin.removeAdminResume",
  "member-admin.setAdminDuesStatus",
  "member-admin.updateAdminMember",
  "member-admin.uploadAdminProfilePicture",
  "member-admin.uploadAdminResume",
  "roles.batchAssign",
  "roles.createLink",
  "roles.syncRole",
  "roles.unlinkRole",
  "roles.updateEmailAudience",
  "roles.updateIssueReminders",
  "roles.updatePermissions",
] as const;

export const HYBRID_ADMIN_PROCEDURES = [
  "forms.createUpload",
  "forms.finalizeUpload",
  "forms.getAttachmentDownload",
  "forms.getLegacyAttachmentDownload",
] as const;

export const EXCLUDED_ADMIN_PROCEDURES = [
  "alumni.listBulletinAdmin",
  "alumni.listLinkableForms",
  "analytics.getReport",
  "audit.catalog",
  "audit.detail",
  "audit.list",
  "audit.searchMembers",
  "career.getAdminCompany",
  "career.listAdminCompanies",
  "email.getSend",
  "email.getTemplate",
  "email.listAudienceOptions",
  "email.listSends",
  "email.listTemplates",
  "email.previewTemplate",
  "email.resolveAudience",
  "event.getAdminEvent",
  "event.getEventFeedback",
  "event.getFeedbackTemplate",
  "event.listAdminEvents",
  "event.listAttendees",
  "event.listAudienceRoles",
  "event.listCheckInEvents",
  "event.listDiscordChannels",
  "event.listDiscordRepairCandidates",
  "event.listEventTags",
  "event.searchCheckInMembers",
  "forms.getAdminForm",
  "forms.getShareAssets",
  "forms.listAdmin",
  "forms.listCallbackExecutions",
  "forms.listCallbacks",
  "forms.listRespondentRoles",
  "forms.listResponses",
  "forms.sectionProvisioning",
  "issues.get",
  "issues.list",
  "issues.listAssignees",
  "issues.listEvents",
  "issues.listHistory",
  "issues.listTeams",
  "issues.listTemplates",
  "member-admin.getAdminMember",
  "member-admin.getAdminMembers",
  "roles.getRole",
  "roles.hasPermission",
  "roles.listDiscordOptions",
  "roles.listLinks",
  "roles.listReminderChannels",
  "roles.listUsers",
  "roles.previewDiscordRole",
] as const;

export type AdminAuditCoverageStatus = "audited" | "excluded" | "hybrid";

export const ADMIN_AUDIT_PROCEDURE_COVERAGE: Readonly<
  Record<string, AdminAuditCoverageStatus>
> = Object.freeze({
  ...Object.fromEntries(
    AUDITED_ADMIN_PROCEDURES.map(
      (procedure) => [procedure, "audited"] as const,
    ),
  ),
  ...Object.fromEntries(
    EXCLUDED_ADMIN_PROCEDURES.map(
      (procedure) => [procedure, "excluded"] as const,
    ),
  ),
  ...Object.fromEntries(
    HYBRID_ADMIN_PROCEDURES.map((procedure) => [procedure, "hybrid"] as const),
  ),
});
