"use client";

import { useState } from "react";
import { Check, Clipboard, Globe2, Loader2, Save } from "lucide-react";

import type { RouterOutputs } from "@forge/api";
import { Badge } from "@forge/ui/badge";
import { Button } from "@forge/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@forge/ui/card";
import { Input } from "@forge/ui/input";
import { Label } from "@forge/ui/label";
import { Switch } from "@forge/ui/switch";
import { toast } from "@forge/ui/toast";

import { api } from "~/trpc/react";

type Detail = RouterOutputs["hackathon"]["get"];

export function PortalConfigurationSection({
  detail,
  isRefreshing,
  onSaved,
}: {
  detail: Detail;
  isRefreshing: boolean;
  onSaved: () => void;
}) {
  const { hackathon, portalClient } = detail;
  const [name, setName] = useState(
    portalClient?.name ?? `${hackathon.displayName} website`,
  );
  const [productionOrigin, setProductionOrigin] = useState(
    portalClient?.productionOrigin ?? "",
  );
  const [enabled, setEnabled] = useState(portalClient?.enabled ?? true);
  const [copied, setCopied] = useState(false);

  const save = api.hackathon.upsertPortalClient.useMutation({
    onError: (error) => toast.error(error.message),
    onSuccess: () => {
      toast.success(
        portalClient ? "Hacker portal saved." : "Hacker portal provisioned.",
      );
      onSaved();
    },
  });

  const busy = save.isPending || isRefreshing;
  const complete = name.trim() !== "" && productionOrigin.trim() !== "";
  const unchanged =
    portalClient !== null &&
    name.trim() === portalClient.name &&
    productionOrigin.trim() === portalClient.productionOrigin &&
    enabled === portalClient.enabled;

  return (
    <Card>
      <CardHeader className="space-y-3">
        <div className="flex flex-wrap items-center gap-2">
          <CardTitle className="flex items-center gap-2">
            <Globe2 className="size-5" aria-hidden="true" /> Hacker portal
          </CardTitle>
          {portalClient ? (
            <Badge variant={portalClient.enabled ? "secondary" : "outline"}>
              {portalClient.enabled ? "Enabled" : "Disabled"}
            </Badge>
          ) : (
            <Badge variant="outline">Not provisioned</Badge>
          )}
        </div>
        <CardDescription>
          Register the themed hackathon website that may use the Hacker SDK. One
          public client belongs to one hackathon and one exact production
          origin.
        </CardDescription>
      </CardHeader>

      <CardContent className="grid gap-4">
        {portalClient ? (
          <div className="grid gap-2 rounded-md border border-white/10 bg-background/60 p-4">
            <p className="text-sm font-medium">Public client ID</p>
            <div className="flex min-w-0 flex-col gap-2 sm:flex-row sm:items-center">
              <code className="min-w-0 flex-1 break-all font-mono text-sm text-muted-foreground">
                {portalClient.clientId}
              </code>
              <Button
                aria-label="Copy public client ID"
                className="min-h-11 shrink-0 gap-2"
                onClick={() => {
                  void navigator.clipboard
                    .writeText(portalClient.clientId)
                    .then(() => {
                      setCopied(true);
                      window.setTimeout(() => setCopied(false), 2_000);
                    })
                    .catch(() => toast.error("Could not copy the client ID."));
                }}
                size="sm"
                type="button"
                variant="secondary"
              >
                {copied ? (
                  <Check className="size-4" aria-hidden="true" />
                ) : (
                  <Clipboard className="size-4" aria-hidden="true" />
                )}
                {copied ? "Copied" : "Copy"}
              </Button>
            </div>
            <p className="text-sm text-muted-foreground">
              Generated by Blade and fixed for the life of this registration. It
              is public; no client secret belongs in the yearly frontend.
            </p>
          </div>
        ) : null}

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="grid gap-2">
            <Label htmlFor="portal-client-name">Portal name</Label>
            <Input
              className="h-11 bg-background/70"
              disabled={busy}
              id="portal-client-name"
              maxLength={120}
              onChange={(event) => setName(event.target.value)}
              placeholder="Knight Hacks X website"
              value={name}
            />
            <p className="text-sm text-muted-foreground">
              Officer-facing label for the registered site.
            </p>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="portal-production-origin">Production origin</Label>
            <Input
              autoCapitalize="none"
              autoCorrect="off"
              className="h-11 bg-background/70 font-mono"
              disabled={busy}
              id="portal-production-origin"
              onChange={(event) => setProductionOrigin(event.target.value)}
              placeholder="https://x.knighthacks.org"
              spellCheck={false}
              type="url"
              value={productionOrigin}
            />
            <p className="text-sm text-muted-foreground">
              Exact HTTPS <span className="font-mono">*.knighthacks.org</span>{" "}
              origin, with no path, port, query, or trailing route.
            </p>
          </div>
        </div>

        <div className="flex min-h-11 items-start justify-between gap-4 rounded-md border border-white/10 bg-background/60 p-4">
          <div className="min-w-0">
            <Label htmlFor="portal-enabled">Allow SDK sign-in</Label>
            <p className="mt-1 text-sm text-muted-foreground">
              Disabling blocks new portal authorization without deleting the
              client ID or its history.
            </p>
          </div>
          <Switch
            aria-label="Allow Hacker SDK sign-in"
            checked={enabled}
            disabled={busy}
            id="portal-enabled"
            onCheckedChange={setEnabled}
          />
        </div>

        <Button
          className="min-h-11 w-fit gap-2"
          disabled={busy || !complete || unchanged}
          onClick={() =>
            save.mutate({
              enabled,
              hackathonId: hackathon.id,
              name: name.trim(),
              productionOrigin: productionOrigin.trim(),
            })
          }
        >
          {save.isPending ? (
            <Loader2 className="size-4 animate-spin" aria-hidden="true" />
          ) : (
            <Save className="size-4" aria-hidden="true" />
          )}
          {portalClient ? "Save portal" : "Provision portal"}
        </Button>
      </CardContent>
    </Card>
  );
}
