export const COMPANIES = [
  "Walmart",
  "Amazon",
  "Apple",
  "UnitedHealth Group",
  "Berkshire Hathaway",
  "CVS Health",
  "Exxon Mobil",
  "Alphabet",
  "McKesson",
  "Cencora",
  "Costco Wholesale",
  "JPMorgan Chase",
  "Microsoft",
  "Cardinal Health",
  "Chevron",
  "Cigna",
  "Ford Motor",
  "Bank of America",
  "General Motors",
  "Elevance Health",
  "Citigroup",
  "Centene",
  "Home Depot",
  "Marathon Petroleum",
  "Kroger",
  "Phillips 66",
  "Fannie Mae",
  "Walgreens Boots Alliance",
  "Valero Energy",
  "Meta Platforms",
  "Verizon Communications",
  "AT&T",
  "Comcast",
  "Wells Fargo",
  "Goldman Sachs Group",
  "Freddie Mac",
  "Target",
  "Humana",
  "State Farm Insurance",
  "Tesla",
  "Morgan Stanley",
  "Johnson & Johnson",
  "Archer Daniels Midland",
  "PepsiCo",
  "United Parcel Service",
  "FedEx",
  "Walt Disney",
  "Dell Technologies",
  "Lowe's",
  "Procter & Gamble",
  "Energy Transfer",
  "Boeing",
  "Albertsons",
  "Sysco",
  "RTX",
  "General Electric",
  "Lockheed Martin",
  "American Express",
  "Caterpillar",
  "MetLife",
  "HCA Healthcare",
  "Progressive",
  "IBM",
  "Deere",
  "Nvidia",
  "StoneX Group",
  "Merck",
  "ConocoPhillips",
  "Pfizer",
  "Delta Air Lines",
  "TD Synnex",
  "Publix Super Markets",
  "Allstate",
  "Cisco Systems",
  "Nationwide",
  "Charter Communications",
  "AbbVie",
  "New York Life Insurance",
  "Intel",
  "TJX",
  "Prudential Financial",
  "HP",
  "United Airlines Holdings",
  "Performance Food Group",
  "Tyson Foods",
  "American Airlines Group",
  "Liberty Mutual Insurance Group",
  "Nike",
  "Oracle",
  "Enterprise Products Partners",
  "Capital One Financial",
  "Plains GP Holdings",
  "World Kinect",
  "AIG",
  "Coca-Cola",
  "TIAA",
  "CHS",
  "Bristol-Myers Squibb",
  "Dow",
  "Best Buy",
  "Thermo Fisher Scientific",
  "Massachusetts Mutual Life Insurance",
  "USAA",
  "General Dynamics",
  "Travelers",
  "Warner Bros. Discovery",
  "U.S. Bancorp",
  "Abbott Laboratories",
  "Northrop Grumman",
  "Northwestern Mutual",
  "Dollar General",
  "PBF Energy",
  "Uber Technologies",
  "Honeywell International",
  "Mondelez International",
  "Starbucks",
  "Qualcomm",
  "Broadcom",
  "US Foods Holding",
  "D.R. Horton",
  "Philip Morris International",
  "Paccar",
  "Salesforce",
  "Nucor",
  "Jabil",
  "Lennar",
  "Eli Lilly",
  "Molina Healthcare",
  "Cummins",
  "Bank of New York Mellon",
  "Netflix",
  "Truist Financial",
  "Arrow Electronics",
  "3M",
  "Visa",
  "Apollo Global Management",
  "HF Sinclair",
  "CBRE Group",
  "PNC Financial Services Group",
  "Lithia Motors",
  "CarMax",
  "Paramount Global",
  "Dollar Tree",
  "United Natural Foods",
  "PayPal Holdings",
  "Penske Automotive Group",
  "Hewlett Packard Enterprise",
  "Duke Energy",
  "Occidental Petroleum",
  "NRG Energy",
  "Amgen",
  "NextEra Energy",
  "Danaher",
  "Gilead Sciences",
  "AutoNation",
  "Kraft Heinz",
  "Avnet",
  "Applied Materials",
  "Southwest Airlines",
  "Charles Schwab",
  "Baker Hughes",
  "McDonald's",
  "Southern Company",
  "Mastercard",
  "Constellation Energy",
  "Hartford Financial Services Group",
  "PG&E",
  "Coupang",
  "EOG Resources",
  "Union Pacific",
  "Rite Aid",
  "Macy's",
  "Marriott International",
  "Lear",
  "Genuine Parts",
  "Sherwin-Williams",
  "Halliburton",
  "Freeport-McMoRan",
  "Live Nation Entertainment",
  "Marsh & McLennan",
  "Advanced Micro Devices",
  "First Citizens BancShares",
  "WESCO International",
  "Carrier Global",
  "Cleveland-Cliffs",
  "Block",
  "Exelon",
  "KKR",
  "CDW",
  "Booking Holdings",
  "Synchrony",
  "Quanta Services",
  "Jones Lang LaSalle",
  "Discover Financial Services",
  "Tenet Healthcare",
  "Altria Group",
  "Stryker",
  "Kimberly-Clark",
  "Waste Management",
  "Cheniere Energy",
  "Ross Stores",
  "WestRock",
  "General Mills",
  "Goodyear Tire & Rubber",
  "BJ's Wholesale Club",
  "GE HealthCare Technologies",
  "Colgate-Palmolive",
  "Whirlpool",
  "L3Harris Technologies",
  "Adobe",
  "Becton Dickinson",
  "Pioneer Natural Resources",
  "Cognizant Technology Solutions",
  "Murphy USA",
  "Fiserv",
  "Parker-Hannifin",
  "American Electric Power",
  "International Paper",
  "ManpowerGroup",
  "Aramark",
  "Steel Dynamics",
  "Aflac",
  "Reinsurance Group of America",
  "Emerson Electric",
  "State Street",
  "PPG Industries",
  "United States Steel",
  "Automatic Data Processing",
  "Group 1 Automotive",
  "Dominion Energy",
  "BlackRock",
  "Oneok",
  "C.H. Robinson Worldwide",
  "Texas Instruments",
  "Kohl's",
  "AutoZone",
  "Lam Research",
  "Corteva",
  "Peter Kiewit Sons'",
  "Builders FirstSource",
  "Kyndryl Holdings",
  "EchoStar",
  "American Family Insurance Group",
  "Delek US Holdings",
  "Land O'Lakes",
  "Sempra",
  "Global Partners",
  "Grainger",
  "Jacobs Solutions",
  "Edison International",
  "MGM Resorts International",
  "Guardian Life Ins. Co. of America",
  "Illinois Tool Works",
  "Ameriprise Financial",
  "PulteGroup",
  "Targa Resources",
  "Ally Financial",
  "BorgWarner",
  "Estée Lauder",
  "Loews",
  "O'Reilly Automotive",
  "Markel Group",
  "Stanley Black & Decker",
  "Micron Technology",
  "Fluor",
  "Leidos Holdings",
  "Viatris",
  "Kinder Morgan",
  "Ecolab",
  "Baxter International",
  "Devon Energy",
  "Kellanova",
  "Farmers Insurance Exchange",
  "Casey's General Stores",
  "IQVIA Holdings",
  "Republic Services",
  "Fox",
  "Gap",
  "Keurig Dr Pepper",
  "Reliance",
  "Asbury Automotive Group",
  "Pacific Life",
  "Vistra",
  "Western & Southern Financial Group",
  "Andersons",
  "Nordstrom",
  "Omnicom Group",
  "Fidelity National Information Services",
  "Consolidated Edison",
  "CSX",
  "AECOM",
  "Lumen Technologies",
  "Tractor Supply",
  "DXC Technology",
  "AGCO",
  "Sonic Automotive",
  "Intuit",
  "United Rentals",
  "Universal Health Services",
  "Boston Scientific",
  "Otis Worldwide",
  "Xcel Energy",
  "Edward Jones",
  "Ball",
  "LKQ",
  "Mutual of Omaha",
  "Mosaic",
  "Textron",
  "Labcorp Holdings",
  "Principal Financial",
  "Regeneron Pharmaceuticals",
  "Raymond James Financial",
  "Dick's Sporting Goods",
  "Auto-Owners Insurance",
  "Expedia Group",
  "J.B. Hunt Transport Services",
  "M&T Bank",
  "DTE Energy",
  "AES",
  "Berry Global Group",
  "Fifth Third Bancorp",
  "Air Products & Chemicals",
  "Corning",
  "EMCOR Group",
  "Amphenol",
  "Westlake",
  "DuPont",
  "Liberty Media",
  "S&P Global",
  "Community Health Systems",
  "FirstEnergy",
  "Unum Group",
  "Henry Schein",
  "Western Digital",
  "Analog Devices",
  "Conagra Brands",
  "Citizens Financial Group",
  "Norfolk Southern",
  "Entergy",
  "W.R. Berkley",
  "DaVita",
  "Northern Trust",
  "Hormel Foods",
  "Crown Holdings",
  "Avis Budget Group",
  "Wayfair",
  "MasTec",
  "Eversource Energy",
  "Newmont",
  "Ryder System",
  "Fidelity National Financial",
  "Molson Coors Beverage",
  "Caesars Entertainment",
  "Lincoln National",
  "VF",
  "International Flavors & Fragrances",
  "Huntington Ingalls Industries",
  "Advance Auto Parts",
  "Public Service Enterprise Group",
  "Ulta Beauty",
  "Hershey",
  "Chewy",
  "American Tower",
  "Mohawk Industries",
  "Assurant",
  "Thor Industries",
  "Graybar Electric",
  "Yum China Holdings",
  "Celanese",
  "Qurate Retail",
  "Williams",
  "Interpublic Group",
  "Ovintiv",
  "Icahn Enterprises",
  "Huntington Bancshares",
  "Erie Insurance Group",
  "Carvana",
  "Hess",
  "Dana",
  "Alcoa",
  "Equitable Holdings",
  "KLA",
  "Darden Restaurants",
  "Autoliv",
  "Alaska Air Group",
  "KeyCorp",
  "Las Vegas Sands",
  "Owens & Minor",
  "Hilton Worldwide Holdings",
  "Ebay",
  "Arthur J. Gallagher",
  "LPL Financial Holdings",
  "Cincinnati Financial",
  "Toll Brothers",
  "Motorola Solutions",
  "Airbnb",
  "Intercontinental Exchange",
  "News Corp.",
  "Chipotle Mexican Grill",
  "Vertex Pharmaceuticals",
  "Biogen",
  "GXO Logistics",
  "SpartanNash",
  "Burlington Stores",
  "Thrivent Financial for Lutherans",
  "NVR",
  "Owens Corning",
  "Westinghouse Air Brake Technologies",
  "Oshkosh",
  "Global Payments",
  "Lululemon athletica",
  "Albemarle",
  "JetBlue Airways",
  "Seaboard",
  "Constellation Brands",
  "Graphic Packaging Holding",
  "Hertz Global Holdings",
  "FM Global",
  "Campbell Soup",
  "Expeditors Intl. of Washington",
  "A-Mark Precious Metals",
  "Booz Allen Hamilton Holding",
  "Quest Diagnostics",
  "Altice USA",
  "PVH",
  "Eastman Chemical",
  "Insight Enterprises",
  "Regions Financial",
  "Beacon Roofing Supply",
  "Rockwell Automation",
  "Polaris",
  "ServiceNow",
  "Sanmina",
  "UGI",
  "WEC Energy Group",
  "BrightSpring Health Services",
  "Cintas",
  "Commercial Metals",
  "Continental Resources",
  "Chesapeake Energy",
  "CenterPoint Energy",
  "NGL Energy Partners",
  "DoorDash",
  "NOV",
  "Zoetis",
  "J.M. Smucker",
  "Microchip Technology",
  "Dover",
  "Diamondback Energy",
  "Avery Dennison",
  "PPL",
  "ON Semiconductor",
  "ARKO",
  "Par Pacific Holdings",
  "APA",
  "Equinix",
  "New York Community Bancorp",
  "Foot Locker",
  "Ingredion",
  "Newell Brands",
  "ABM Industries",
  "Securian Financial Group",
  "Prologis",
  "Blackstone",
  "Skechers U.S.A.",
  "Masco",
  "Rush Enterprises",
  "Franklin Resources",
  "ODP",
  "American Financial Group",
  "Packaging Corp. of America",
  "Vulcan Materials",
  "Interactive Brokers Group",
  "Williams-Sonoma",
  "XPO",
  "Weyerhaeuser",
  "Genworth Financial",
  "CMS Energy",
  "Science Applications International",
  "Jefferies Financial Group",
  "Bath & Body Works",
  "Electronic Arts",
  "Taylor Morrison Home",
  "Zimmer Biomet Holdings",
  "Clorox",
  "Xylem",
  "Voya Financial",
  "Fastenal",
  "Watsco",
  "Workday",
  "Old Republic International",
  "RPM International",
  "UFP Industries",
  "Ameren",
  "Knight-Swift Transportation Hldgs.",
  "Monster Beverage",
  "Intuitive Surgical",
  "Super Micro Computer",
  "Concentrix",
  "O-I Glass",
  "Yum Brands",
  "Domtar",
  "CommScope Holding",
  "Post Holdings",
  "Crown Castle",
  "Avantor",
  "KBR",
  "Opendoor Technologies",
  "APi Group",
  "EQT",
  "EnLink Midstream",
  "Palo Alto Networks",
  "Xerox Holdings",
  "Ingersoll Rand",
  "Dillard's",
  "Martin Marietta Materials",
  "Vertiv Holdings",
  "Moderna",
  "Boise Cascade",
  "Sprouts Farmers Market",
  "Agilent Technologies",
  "Olin",
  "Darling Ingredients",
  "Sonoco Products",
  "CACI International",
  "Core & Main",
  "Marathon Oil",
  "Hyatt Hotels",
  "Select Medical Holdings",
  "McCormick",
  "Tapestry",
  "Coca-Cola Consolidated",
  "Howmet Aerospace",
  "Welltower",
  "CF Industries Holdings",
  "Ametek",
  "TransDigm Group",
  "Wynn Resorts",
  "Southwestern Energy",
  "Amkor Technology",
  "Insperity",
  "Patterson",
  "T. Rowe Price",
  "Ralph Lauren",
  "KB Home",
  "Brunswick",
  "Robert Half",
  "PENN Entertainment",
  "NetApp",
  "Organon",
  "Petco Health and Wellness",
  "Regal Rexnord",
  "Resideo Technologies",
  "Camping World Holdings",
  "Huntsman",
  "Victoria's Secret",
  "Levi Strauss",
  "Roper Technologies",
  "Academy Sports and Outdoors",
  "Meritage Homes",
  "American Axle & Manufacturing",
  "Fortive",
  "Nasdaq",
  "Broadridge Financial Solutions",
  "Spirit AeroSystems Holdings",
  "Warner Music Group",
  "Chemours",
  "ADT",
  "Edwards Lifesciences",
  "First American Financial",
  "Hanover Insurance Group",
  "Silgan Holdings",
  "Endeavor Group Holdings",
  "Moody's",
  "Coterra Energy",
  "Gartner",
  "Under Armour",
  "Ingles Markets",
  "Church & Dwight",
  "Old Dominion Freight Line",
  "U-Haul Holding",
  "Oscar Health",
  "Arista Networks",
  "Synopsys",
  "Harley-Davidson",
  "Frontier Communications",
  "Primoris Services",
  "Carlisle",
  "Simon Property Group",
  "Hanesbrands",
  "Anywhere Real Estate",
  "Teledyne Technologies",
  "CME Group",
  "Juniper Networks",
  "Coty",
  "Pool",
  "Evergy",
  "Marvell Technology",
  "NiSource",
  "SS&C Technologies Holdings",
  "Schneider National",
  "Autodesk",
  "Sealed Air",
  "Iron Mountain",
  "Digital Realty Trust",
  "Keysight Technologies",
  "Globe Life",
  "Parsons",
  "Mattel",
  "Southwest Gas Holdings",
  "CUNA Mutual Group (TruStage)",
  "Clean Harbors",
  "Cornerstone Building Brands",
  "Hubbell",
  "Spirit Airlines",
  "Lamb Weston Holdings",
  "Take-Two Interactive Software",
  "GMS",
  "Penn Mutual Life Insurance",
  "Landstar System",
  "Host Hotels & Resorts",
  "Fortinet",
  "OneMain Holdings",
  "GameStop",
  "Equifax",
  "American Eagle Outfitters",
  "Comerica",
  "Greif",
  "Comfort Systems USA",
  "TopBuild",
  "Bread Financial Holdings",
  "Coherent",
  "Telephone & Data Systems",
  "Stifel Financial",
  "Urban Outfitters",
  "Terex",
  "Ryerson Holding",
  "Snap-on",
  "Flowers Foods",
  "First Horizon",
  "Paychex",
  "Hasbro",
  "Sentry Insurance Group",
  "Ares Management",
  "Lennox International",
  "Peabody Energy",
  "Kemper",
  "Nexstar Media Group",
  "TelevisaUnivision",
  "Tempur Sealy International",
  "TriNet Group",
  "Worthington Enterprises",
  "Maximus",
  "Compass",
  "Brink's",
  "Kelly Services",
  "Navient",
  "Puget Energy",
  "AMC Entertainment Holdings",
  "Encompass Health",
  "Skyworks Solutions",
  "Timken",
  "Liberty Energy",
  "Marriott Vacations Worldwide",
  "Leggett & Platt",
  "Big Lots",
  "Weis Markets",
  "Pinnacle West Capital",
  "EPAM Systems",
  "Antero Resources",
  "Bloomin' Brands",
  "MDU Resources Group",
  "MDC Holdings",
  "Texas Roadhouse",
  "Mercury General",
  "Fortune Brands Innovations",
  "Zions Bancorp.",
  "JELD-WEN Holding",
  "Snap",
  "Zebra Technologies",
  "Agilon Health",
  "Toro",
  "Zoom Video Communications",
  "Tetra Tech",
  "Public Storage",
  "Illumina",
  "Ventas",
  "FMC",
  "ArcBest",
  "Domino's Pizza",
  "ASGN",
  "Rivian Automotive",
  "Elanco Animal Health",
  "Graham Holdings",
  "Floor & Decor Holdings",
  "Applied Industrial Technologies",
  "PriceSmart",
  "Lyft",
  "Ciena",
  "IAC",
  "Country Financial",
  "Western Union",
  "Flowserve",
  "Western Alliance Bancorp.",
  "Option Care Health",
  "SiteOne Landscape Supply",
  "Topgolf Callaway Brands",
  "eXp World Holdings",
  "Abercrombie & Fitch",
  "Atmos Energy",
  "Catalent",
  "Brown & Brown",
  "GoDaddy",
  "American Water Works",
  "Selective Insurance Group",
  "Brown-Forman",
  "Advantage Solutions",
  "ResMed",
  "Splunk",
  "Plexus",
  "Hub Group",
  "Lincoln Electric Holdings",
  "NCR Atleos",
  "Calumet",
  "Dycom Industries",
  "Valmont Industries",
  "ATI",
  "Twilio",
  "CNO Financial Group",
  "Patterson-UTI Energy",
  "Brinker International",
  "Charles River Laboratories International",
  "Hyster-Yale",
  "Brighthouse Financial",
  "Service Corp. International",
  "CrossAmerica Partners",
  "Cadence",
  "MillerKnoll",
  "Realty Income",
  "Middleby",
  "M/I Homes",
  "Hologic",
  "Alliant Energy",
  "Generac Holdings",
  "MSC Industrial Direct",
  "Rocket Companies",
  "Upbound Group",
  "East West Bancorp",
  "Hilton Grand Vacations",
  "Grocery Outlet Holding",
  "Dentsply Sirona",
  "V2X",
  "Crocs",
  "Spectrum Brands Holdings",
  "Visteon",
  "Acuity Brands",
  "Greenbrier",
  "Webster Financial",
  "Cabot",
  "RXO",
  "Chord Energy",
  "Popular",
  "Garrett Motion",
  "Tutor Perini",
  "Copart",
  "Toast",
  "Align Technology",
  "A.O. Smith",
  "TransUnion",
  "NCR Voyix",
  "Akamai Technologies",
  "Trimble",
  "Medical Mutual of Ohio",
  "AMN Healthcare Services",
  "Mettler-Toledo International",
  "ScanSource",
  "LCI Industries",
  "Cboe Global Markets",
  "Diebold Nixdorf",
  "ChampionX",
  "Corpay",
  "iHeartMedia",
  "Travel + Leisure",
  "Dream Finders Homes",
  "Boyd Gaming",
  "NLV Financial",
  "Ensign Group",
  "Sally Beauty Holdings",
  "Conduent",
  "Sylvamo",
  "Tri Pointe Homes",
  "EnerSys",
  "Incyte",
  "Century Communities",
  "Rithm Capital",
  "Euronet Worldwide",
  "Hawaiian Electric Industries",
  "DraftKings",
  "IDEXX Laboratories",
  "MYR Group",
  "Deckers Outdoor",
  "DexCom",
  "MKS Instruments",
  "VICI Properties",
  "Cooper Cos.",
  "Frontier Group Holdings",
  "Qorvo",
  "Five Below",
  "TreeHouse Foods",
  "Scotts Miracle-Gro",
  "Atlassian",
  "Entegris",
  "Atkore",
  "H.B. Fuller",
  "Granite Construction",
  "Winnebago Industries",
  "FTI Consulting",
  "AptarGroup",
  "Columbia Sportswear",
  "Roku",
  "Civitas Resources",
  "H&R Block",
  "Alpha Metallurgical Resources",
  "Patrick Industries",
  "Murphy Oil",
  "Synovus Financial",
  "Cracker Barrel Old Country Store",
  "Cheesecake Factory",
  "CNX Resources",
  "Chefs' Warehouse",
  "Donaldson",
  "Mueller Industries",
  "MRC Global",
  "Chart Industries",
  "Alight",
  "Vishay Intertechnology",
  "Range Resources",
  "Valley National Bancorp",
  "Match Group",
  "Gen Digital",
  "Wintrust Financial",
  "Moog",
  "First Solar",
  "Central Garden & Pet",
  "Green Plains",
  "Werner Enterprises",
  "AppLovin",
  "ITT",
  "Herc Holdings",
  "Gray Television",
  "IDEX",
  "Boston Properties",
  "Pitney Bowes",
  "Steelcase",
  "Sun Communities",
  "AdaptHealth",
  "Vertex Energy",
  "Genesis Energy",
  "Jackson Financial",
  "FirstCash Holdings",
  "Cal-Maine Foods",
  "Arch Resources",
  "Avient",
  "Cano Health",
  "BlueLinx Holdings",
  "Sinclair",
  "BOK Financial",
  "Permian Resources",
  "PACS Group",
  "Coinbase Global",
  "Western Midstream Partners",
  "Federated Mutual Insurance",
  "G-III Apparel Group",
  "Vontier",
  "Matson",
  "Kirby",
  "Kaiser Aluminum",
  "Vista Outdoor",
  "Designer Brands",
  "Rollins",
  "Advanced Drainage Systems",
  "Cinemark Holdings",
  "CrowdStrike",
  "Pinterest",
  "Instacart",
  "Hillenbrand",
  "Allison Transmission Holdings",
  "RH",
  "Brookdale Senior Living",
  "QuidelOrtho",
  "Trinity Industries",
  "Teleflex",
  "HEICO",
  "Bruker",
  "Carlyle Group",
  "Energizer Holdings",
  "Quad/Graphics",
  "Rackspace Technology",
  "Waters",
  "West Pharmaceutical Services",
  "Carter's",
  "NeueHealth",
  "SkyWest",
  "Acadia Healthcare",
  "Revvity",
  "Portland General Electric",
  "Woodward",
  "TEGNA",
  "Sabre",
  "Light & Wonder",
  "Vail Resorts",
  "Radius Recycling",
  "PennyMac Financial Services",
  "Saia",
  "Equity Residential",
  "Helmerich & Payne",
  "Korn Ferry",
  "PC Connection",
  "Curtiss-Wright",
  "SLM",
  "Benchmark Electronics",
  "American National Group",
  "Pure Storage",
  "Knife River",
  "Caleres",
  "BrightView Holdings",
  "Cooper-Standard Holdings",
  "Primerica",
  "F5",
  "Matador Resources",
  "Snowflake",
  "Viasat",
  "California Resources",
  "Peloton Interactive",
  "Roblox",
  "Installed Building Products",
  "First National of Nebraska",
  "Guess",
  "ESAB",
  "Amica Mutual Insurance",
  "AvalonBay Communities",
  "DocuSign",
  "Titan Machinery",
  "ModivCare",
  "Hovnanian Enterprises",
  "Etsy",
  "Adams Resources & Energy",
  "Surgery Partners",
  "Columbia Banking System",
  "Verisk",
  "MasterBrand",
  "Hawaiian Holdings",
  "AMC Networks",
  "SBA Communications",
  "Americold Realty Trust",
  "NewMarket",
  "Park Hotels & Resorts",
  "Alexandria Real Estate Equities",
  "Griffon",
  "Air Lease",
  "UL Solutions",
  "Teradyne",
  "OGE Energy",
  "Bio-Rad Laboratories",
  "Spire",
  "Gannett",
  "Stericycle",
  "Cullen/Frost Bankers",
  "Extra Space Storage",
  "REV Group",
  "ProFrac Holding",
  "Nordson",
  "Summit Materials",
  "Valvoline",
  "Kontoor Brands",
  "Skyline Champion",
  "Teladoc Health",
  "Louisiana-Pacific",
  "Universal",
  "Consol Energy",
  "Encore Wire",
  "Playtika Holding",
  "Alliance Resource Partners",
  "Envista Holdings",
  "Shift4 Payments",
  "Talen Energy",
  "Carpenter Technology",
  "WEX",
  "Old National Bancorp",
  "AGNC Investment",
  "Wabash National",
  "MSCI",
  "Stagwell",
  "Mativ Holdings",
  "Belden",
  "Allegiant Travel",
  "Dropbox",
  "Exact Sciences",
  "BWX Technologies",
  "Clear Channel Outdoor Hldgs.",
] as const;
